apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - base/service.yaml
  - base/deployment.yaml
  - base/ingress.yaml
  - certificate_keycloak.yaml
### Sealed Secrets
  - sealedsecret_keycloak-admin.yaml
  - sealedsecret_keycloak-database.yaml

configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_DB=postgres
      - KC_DB_URL_HOST=private-denic0la-pg-do-user-15913621-0.j.db.ondigitalocean.com
      - KC_DB_URL_PORT=25060
      - KC_DB_URL_DATABASE=keycloak
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME=https://keycloak.denic0la.ch
      - KC_HOSTNAME_STRICT=true
      - KC_DB_POOL_INITIAL_SIZE=1
      - KC_DB_POOL_MAX_SIZE=6
      - KC_DB_URL_PROPERTIES=?sslmode=require

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/keycloak/keycloak
    newTag: "26.6.1"
