---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgCdYggrqsCbGdcCB8Lt7+5Tk0fli5JadML21T9B3ys/JCoQ3jIRpsmHsg9ivL7k+Qqs/KZbXh0Pi1qhDdtO7nYSHNIHI57aRhK9EL6KOpA5tLDAzHfVhGiMdnahMS2k4wqpkn+BdDjpmVQYpVdtCbgqZH8ixO0T/PDXQuBgykR3BhEwMDZl16ujdXEtQLzXxohDX9OF2u6luXiRp/FmEeefarguPBpxT677rPd6sZNQ1lqB7uBReC1yruuhLgQbbnWrqzGyBlLDp20e5fz9FYDBPmz1jBX/OAVwhuFRlKnDWZ2C0PW5YR/dOWo05l6cyAu5z05XEyiMxnV41gcEb7xna57eaOUr1Xfc0HJZILiVB1fiyWYh1rH6I6/dcxyF4mACd9pKIa/u/vWYmCWr2flCebmc+RETd2saybdxsQxU3QWdB/R9kiiOdsqtrP2SdS67ued+WNsVg+sCu3ukz35Rel8sunioXgRYuTIgl9fLxhHZ9ZfNsDT13N9sssVd9h2WkrqTHPmv8ZwMfHmPj/8gU8cCWdpRvnA+9xqeA4zJImN9w0zfc+hPMgj0U3WWLsVKbXZ5fwdD91uT+say1FoSIObIQ+PuWmO8WHUzLouD8Pbli4rCm/QHdNyAM51v7fCpl1VwG+754d8WaCw1u+nn8qjdP8CG/++GaYQIU5gERMKR3mtSFa5qkSXNGZ7Jii8Zpr0+hYMuchZwOXB08WvKJmlYYvRfe/iw5z4Z2AE=
    username: AgBFL/jiW24HPccv9r7QhTSyhmPIc/SkOi5cjnwWdm6nlqbuBZWABL9icFaF7MtZH+qab7CWbRgt5/nzod71BUfc3VzDq1R0jDigjNZMFVKMoxJS95il4GsLULkcwOEqGEdWNBdPy8XdWlxm4ZLftc0K3WjMqg5Obu2ojxMbs417HZO3+AwU8FwT5d6WKzM2fmZQXGbnpfh/voDOFXlaA/7fL7jTdAmMjhIYXVOKbvH8iMSXNE9sDMuj2JPDNN7m1vrMTDsUYQhQvJSnRl8WN9uMH6NJqwwYkzjHEnlwdtKQ5NJIUE6C6SoH0HMWw8iFaQLm3qN4s44Lr+hAftSULt76oYmsGGbma2od2wTybt29AII0/HGIVQQhEwkpk11dnA1EuhbXRymSBl9jJhFYWK+aL/yzIDUkWHrkILJX3L0rgkWBw5ioKOJWnJNL0KBQ/6K8HSY0JjLvYgpfInoVeu1KoZ1BEzoiijjr2KgTJxmk8mYp9ndbWBFg2074VepX8Vg2GOfLG6tKKXOIjJPkRujKoG73i+200vMKz0XLpyPVtlCbOUpscQxFj/S0onC2VfsvDXihcMa6ZbDue48Up8+hynl+7yRG6TlfFojpxAAWDJFXas7aKVgi2o4dEcvW3DNmhqydbJc83wUtUtOlMV1vTW8GgVyZPpKeO2MaWTYWUsX87KGb4hLX9pQmrRQkNB2vcLKTXg==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
    type: Opaque
