---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  encryptedData:
    password: AgCMnGqPgfOeaf/s6sp/vVRNYdxGscsIK7wAfFbHt4Llw7oyx3T1Jo52w5roMlV1qzBkt+Bj3bKD2ApijJ2EPtv6H+5Pj3Fo3W8YzTcRJnA9naT5NStssQg6MVGeEpZmdbyaXbOWMC2kPGkf2ThzTpDJhDvfDTmwoEtq8hMv63P+6hT0gUXhNktKtpyO5b3uvrK23KtZ/xADjnWAFfeQhqubBAWeXlcHxBCYhWXV/3lhlV/XRceyWJfT4t0NE3U7v4kdHyTdVIuxcHsxbrZ56NlO4tlPNziSfsb45rrUcS0z4bY17sq0lTQzuU0/kK9H1bBMY/M2tILk5H8giS7Rxsl+c2SEh9/Tcioc2u2/RGzvHKZ9YXmbKXvNFifUArDkhySvqsTBLGnS6DfVMUBzkc0mMyJHE0g+h/urVJz5Zp+37nSzt0LgSzyEL3A8P9DWq6TOFiIFMaYeQ8JEfVZuDFZ1wKVuamXYO3dVfpWa87OEMwZ4sZZcHk/49GG/4lFpIuPtmCLuVhGmJy3Sp6RpLGk/zZaW8m29MJUFiw81x7wopPlLHg72HWoo5qirLCKKBho+4MuxqWnIFMOeSkk9MEF2OQVOEsZEGa6gfO/XTV1X7ATr2t409CLd+4yfzw7xkOMOuEdPEY5BjCZAzRSsd+z6/S18rdVduGAK8F5nwbt9vQhDW8RSHt4FiHKWKsbaEP2qawe2UNqM9c7bBMBjCm5vKiIMH80BaOo=
    username: AgAILVzGausXst8L3V2wqsjxIGM89UP8BbQKfXecU5584ob95Tx/7MIn6aAsOfQLwljjMLj89UQ3YkH49hMsATHfAqWG3MYpi81hlThY8wcNrz9NoBxHY619nt/nrl8dhUwZZq2vjZMocfbmTkYsmCWb6wL2UbDPC+aGC5nyYtxFicec0QRMcAg1wwPpoIf1zF/2nDhd2+bq62B8F5TpQEwe35dsK79BnKR7Ci8szGrb++3qD5QAJPZrIymYw1avudn9nPbCrIYUS8ItJoWONZvV58BLpiKF6kSiQi0w1wHZszmJUj0yRfMybi/Q7izFNcePUW53sQZS1/KzdJQxieaarviBDvO/Re4XlK8Q+9a3K7w62leq3yoFveOQWbI1WaZ9tjFOSybPLj1k0HwKf5KL7ivxA9pYadabblH0xPsS6JBTJNvmQtuAadpU8zZs8B/sjjLrf/5DqrrmZsecOJqj+bWL3AivCl9pHyrD8sSBjW9LjebUFAZ6vg8/PsNvFfqb98xsi+YLubzRMPAdC4+IcamjkrxRbMzmaKkyidQcceBtnx9cRLOVR6sNRenXNUlYWCMl2UPxyVjhzmkOxE7JXcMuB6O5LZ2r5F2fSea0WSKkIGmplf8qWsw/dGL90aAG6UGf8RZaJFJZwi62O0V7TIsT0/GgSQc4zY1BD0AcF8+PricsbwyYvq3rnJTGcVeIWJ9tAlikjw==
  template:
    metadata:
      name: keycloak-database
      namespace: keycloak
    type: Opaque
